<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519111640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add license table with seed data and license_id FK to content';
    }

    public function up(Schema $schema): void
    {
        // comment_like + fk_parent_comment_id → Version20260512120000
        // is_verified                          → Version20260505095128
        // pending_email                        → Version20260512000000

        $this->addSql('CREATE TABLE license (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_code VARCHAR(20) NOT NULL, full_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5768F41917D2FE0D ON license (short_code)');
        $this->addSql("INSERT INTO license (short_code, full_name) VALUES
            ('CC BY',       'CC BY – Namensnennung 4.0 International'),
            ('CC BY-SA',    'CC BY-SA – Namensnennung-Share Alike 4.0 International'),
            ('CC BY-ND',    'CC BY-ND – Namensnennung-Keine Bearbeitungen 4.0 International'),
            ('CC BY-NC',    'CC BY-NC – Namensnennung-Nicht kommerziell 4.0 International'),
            ('CC BY-NC-SA', 'CC BY-NC-SA – Namensnennung-Nicht kommerziell-Share Alike 4.0 International'),
            ('CC BY-NC-ND', 'CC BY-NC-ND – Namensnennung-Nicht kommerziell-Keine Bearbeitungen 4.0 International')
        ");
        $this->addSql('ALTER TABLE content ADD license_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A9460F904B FOREIGN KEY (license_id) REFERENCES license (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FEC530A9460F904B ON content (license_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE content DROP CONSTRAINT FK_FEC530A9460F904B');
        $this->addSql('DROP INDEX IDX_FEC530A9460F904B');
        $this->addSql('ALTER TABLE content DROP license_id');
        $this->addSql('DROP TABLE license');
    }
}