<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526084822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_comment_parent RENAME TO IDX_9474526C711D77BB');
        $this->addSql('ALTER INDEX idx_comment_like_user RENAME TO IDX_8A55E25F5741EEB9');
        $this->addSql('ALTER INDEX idx_comment_like_comment RENAME TO IDX_8A55E25F807B780');
        $this->addSql('ALTER INDEX idx_content_license_id RENAME TO IDX_FEC530A9460F904B');
        $this->addSql('ALTER TABLE license ADD description VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE license ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE license ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_license_short_code RENAME TO UNIQ_5768F41917D2FE0D');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_9474526c711d77bb RENAME TO idx_comment_parent');
        $this->addSql('ALTER INDEX idx_8a55e25f807b780 RENAME TO idx_comment_like_comment');
        $this->addSql('ALTER INDEX idx_8a55e25f5741eeb9 RENAME TO idx_comment_like_user');
        $this->addSql('ALTER INDEX idx_fec530a9460f904b RENAME TO idx_content_license_id');
        $this->addSql('ALTER TABLE license DROP description');
        $this->addSql('ALTER TABLE license ALTER id SET DEFAULT nextval(\'license_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE license ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_5768f41917d2fe0d RENAME TO uniq_license_short_code');
    }
}
