<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316123819 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE content_tag DROP CONSTRAINT content_tag_pkey');
        $this->addSql('ALTER TABLE content_tag DROP id');
        $this->addSql('ALTER TABLE content_tag ADD PRIMARY KEY (fk_content_id, fk_tag_id)');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT favorite_pkey');
        $this->addSql('ALTER TABLE favorite DROP id');
        $this->addSql('ALTER TABLE favorite ADD PRIMARY KEY (fk_user_id, fk_content_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE content_tag DROP CONSTRAINT content_tag_pkey');
        $this->addSql('ALTER TABLE content_tag ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE content_tag ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT favorite_pkey');
        $this->addSql('ALTER TABLE favorite ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE favorite ADD PRIMARY KEY (id)');
    }
}
