<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260310120407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fk_user_id INT NOT NULL, fk_content_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526C5741EEB9 ON comment (fk_user_id)');
        $this->addSql('CREATE INDEX IDX_9474526C74CE697E ON comment (fk_content_id)');
        $this->addSql('CREATE TABLE content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, file_path VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fk_user_id INT NOT NULL, fk_category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEC530A95741EEB9 ON content (fk_user_id)');
        $this->addSql('CREATE INDEX IDX_FEC530A97BB031D6 ON content (fk_category_id)');
        $this->addSql('CREATE TABLE content_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fk_content_id INT NOT NULL, fk_tag_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B662E17674CE697E ON content_tag (fk_content_id)');
        $this->addSql('CREATE INDEX IDX_B662E1769A7C0B81 ON content_tag (fk_tag_id)');
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fk_user_id INT NOT NULL, fk_content_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED95741EEB9 ON favorite (fk_user_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED974CE697E ON favorite (fk_content_id)');
        $this->addSql('CREATE TABLE rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, fk_user_id INT NOT NULL, fk_content_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D88926225741EEB9 ON rating (fk_user_id)');
        $this->addSql('CREATE INDEX IDX_D889262274CE697E ON rating (fk_content_id)');
        $this->addSql('CREATE TABLE reason (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fk_content_id INT DEFAULT NULL, fk_comment_id INT DEFAULT NULL, fk_reason_id INT NOT NULL, fk_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F778474CE697E ON report (fk_content_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784807B780 ON report (fk_comment_id)');
        $this->addSql('CREATE INDEX IDX_C42F778438E2C202 ON report (fk_reason_id)');
        $this->addSql('CREATE INDEX IDX_C42F77845741EEB9 ON report (fk_user_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C5741EEB9 FOREIGN KEY (fk_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C74CE697E FOREIGN KEY (fk_content_id) REFERENCES content (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A95741EEB9 FOREIGN KEY (fk_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A97BB031D6 FOREIGN KEY (fk_category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_tag ADD CONSTRAINT FK_B662E17674CE697E FOREIGN KEY (fk_content_id) REFERENCES content (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE content_tag ADD CONSTRAINT FK_B662E1769A7C0B81 FOREIGN KEY (fk_tag_id) REFERENCES tag (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED95741EEB9 FOREIGN KEY (fk_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED974CE697E FOREIGN KEY (fk_content_id) REFERENCES content (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926225741EEB9 FOREIGN KEY (fk_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D889262274CE697E FOREIGN KEY (fk_content_id) REFERENCES content (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778474CE697E FOREIGN KEY (fk_content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784807B780 FOREIGN KEY (fk_comment_id) REFERENCES comment (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778438E2C202 FOREIGN KEY (fk_reason_id) REFERENCES reason (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77845741EEB9 FOREIGN KEY (fk_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C5741EEB9');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C74CE697E');
        $this->addSql('ALTER TABLE content DROP CONSTRAINT FK_FEC530A95741EEB9');
        $this->addSql('ALTER TABLE content DROP CONSTRAINT FK_FEC530A97BB031D6');
        $this->addSql('ALTER TABLE content_tag DROP CONSTRAINT FK_B662E17674CE697E');
        $this->addSql('ALTER TABLE content_tag DROP CONSTRAINT FK_B662E1769A7C0B81');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED95741EEB9');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED974CE697E');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D88926225741EEB9');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D889262274CE697E');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778474CE697E');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784807B780');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778438E2C202');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F77845741EEB9');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE content_tag');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP TABLE rating');
        $this->addSql('DROP TABLE reason');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
    }
}
